services:
  influxdb:
    image: influxdb:2
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      # InfluxDB lit les variables d'environnement depuis le .env
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUX_ADMIN_USER}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUX_ADMIN_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=PolySource
      - DOCKER_INFLUXDB_INIT_BUCKET=polysource_data
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUX_ADMIN_TOKEN}
    volumes:
      - ./influxdb_data:/var/lib/influxdb2
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    user: "472:472"
    ports:
      - "3000:3000"
    environment:
      # On passe le token à Grafana pour le provisioning
      - INFLUX_TOKEN=${INFLUX_ADMIN_TOKEN}
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
      - GF_INSTALL_PLUGINS=volkovlabs-echarts-panel
    volumes:
      - ./grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
    restart: always

  telegraf:
    image: telegraf
    container_name: telegraf
    environment:
      # On passe les variables à Telegraf pour sa configuration
      - INFLUX_TOKEN=${INFLUX_ADMIN_TOKEN}
      - MQTT_USER=${MQTT_USER}
      - MQTT_PASSWORD=${MQTT_PASSWORD}
      - MQTT_SERVER=${MQTT_SERVER}
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - influxdb
    restart: always
