# Configuration globale
[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  precision = ""
  hostname = "telegraf-container"
  omit_hostname = false

[[inputs.mqtt_consumer]]
  servers = ["ssl://4ce3ae5fec044cfbb33a7989f49a7bd6.s1.eu.hivemq.cloud:8883"]
  username = "Polysource"
  password = "Polysource2025"
  topics = ["source/mesures"]
  data_format = "json"
  json_time_key = "timestamp"
  json_time_format = "unix"

  #Configuration à faire selon le format des données envoyées par l'ESP32
  tag_keys = ["device_id", "location"]

[[outputs.influxdb_v2]]
  urls = ["http://influxdb:8086"]
  token = "L-oNnv-34ivEIY_h5bTZXiUYx7yTxUiE8oivZK8jeyP-9JXo5yQ1gYEHuPa7Hs9BHL2X9OGBpfwatKwsEtaajg=="
  organization = "PolySource"
  bucket = "polysource_data"
