{
 "title": "PolySource",
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Batterie",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"polysource_data\")\n  |> range(start: 0)  // ou une période large pour inclure toutes les données\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => r[\"_field\"] == \"battery_percent\")\n  |> filter(fn: (r) => r[\"device_id\"] == \"source01\")\n  |> filter(fn: (r) => r[\"host\"] == \"telegraf-container\")\n  |> last()"
    }
   ]
  },
  {
   "title": "Débit",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 13, "w": 18, "x": 6, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"polysource_data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => r[\"_field\"] == \"flow_rate_l_min\")\n  |> filter(fn: (r) => r[\"device_id\"] == \"source01\")\n  |> filter(fn: (r) => r[\"host\"] == \"telegraf-container\")\n  |> group(columns: [\"_measurement\", \"device_id\", \"host\"])  // Assure de grouper par ces colonnes\n"
    }
   ]
  },
  {
   "title": "Niveau d'eau",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 5 },
   "targets": [
    {
     "query": "from(bucket: \"polysource_data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => r[\"_field\"] == \"water_level_cm\")\n  |> filter(fn: (r) => r[\"device_id\"] == \"source01\")\n  |> filter(fn: (r) => r[\"host\"] == \"telegraf-container\")\n  |> last()"
    }
   ]
  },
  {
   "title": "Evolution Niveau d'Eau",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "query": "from(bucket: \"polysource_data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => r[\"_field\"] == \"water_level_cm\")\n  |> filter(fn: (r) => r[\"device_id\"] == \"source01\")\n  |> filter(fn: (r) => r[\"host\"] == \"telegraf-container\")\n  |> group(columns: [\"_measurement\", \"device_id\", \"host\"])  // Assure de grouper par ces colonnes\n"
    }
   ]
  }
 ]
}